// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Common/msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event int32

const (
	Event_EVENT_MSG_INFO                Event = 0
	Event_EVENT_REGISTER_REQ            Event = 1
	Event_EVENT_REGISTER_REP            Event = 2
	Event_EVENT_LOGIN_REQ               Event = 3
	Event_EVENT_LOGIN_REP               Event = 4
	Event_EVENT_ADD_ONE_INFO            Event = 5
	Event_EVENT_QUERY_INFO_REQ          Event = 6
	Event_EVENT_RETURN_INFO_LIST        Event = 7
	Event_EVENT_CHANGE_INFO_REQ         Event = 8
	Event_EVENT_CHANGE_INFO_REP         Event = 9
	Event_EVENT_DEL_INFO_REQ            Event = 10
	Event_EVENT_DEL_INFO_REP            Event = 11
	Event_EVENT_STATISYICAL_INFO_CHANGE Event = 12
)

var Event_name = map[int32]string{
	0:  "EVENT_MSG_INFO",
	1:  "EVENT_REGISTER_REQ",
	2:  "EVENT_REGISTER_REP",
	3:  "EVENT_LOGIN_REQ",
	4:  "EVENT_LOGIN_REP",
	5:  "EVENT_ADD_ONE_INFO",
	6:  "EVENT_QUERY_INFO_REQ",
	7:  "EVENT_RETURN_INFO_LIST",
	8:  "EVENT_CHANGE_INFO_REQ",
	9:  "EVENT_CHANGE_INFO_REP",
	10: "EVENT_DEL_INFO_REQ",
	11: "EVENT_DEL_INFO_REP",
	12: "EVENT_STATISYICAL_INFO_CHANGE",
}

var Event_value = map[string]int32{
	"EVENT_MSG_INFO":                0,
	"EVENT_REGISTER_REQ":            1,
	"EVENT_REGISTER_REP":            2,
	"EVENT_LOGIN_REQ":               3,
	"EVENT_LOGIN_REP":               4,
	"EVENT_ADD_ONE_INFO":            5,
	"EVENT_QUERY_INFO_REQ":          6,
	"EVENT_RETURN_INFO_LIST":        7,
	"EVENT_CHANGE_INFO_REQ":         8,
	"EVENT_CHANGE_INFO_REP":         9,
	"EVENT_DEL_INFO_REQ":            10,
	"EVENT_DEL_INFO_REP":            11,
	"EVENT_STATISYICAL_INFO_CHANGE": 12,
}

func (x Event) String() string {
	return proto.EnumName(Event_name, int32(x))
}

func (Event) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{0}
}

// 枚举的第一个字段必须为0
type CodeType int32

const (
	CodeType_ERR CodeType = 0
	CodeType_SUC CodeType = 1
)

var CodeType_name = map[int32]string{
	0: "ERR",
	1: "SUC",
}

var CodeType_value = map[string]int32{
	"ERR": 0,
	"SUC": 1,
}

func (x CodeType) String() string {
	return proto.EnumName(CodeType_name, int32(x))
}

func (CodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{1}
}

type Code struct {
	Code                 CodeType `protobuf:"varint,1,opt,name=code,proto3,enum=CodeType" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{0}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetCode() CodeType {
	if m != nil {
		return m.Code
	}
	return CodeType_ERR
}

func (m *Code) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type Info struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time                 int32    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Usetype              string   `protobuf:"bytes,3,opt,name=usetype,proto3" json:"usetype,omitempty"`
	Val                  float32  `protobuf:"fixed32,4,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{2}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Info) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Info) GetUsetype() string {
	if m != nil {
		return m.Usetype
	}
	return ""
}

func (m *Info) GetVal() float32 {
	if m != nil {
		return m.Val
	}
	return 0
}

type StatisticalInfo struct {
	WeekVal              float32  `protobuf:"fixed32,1,opt,name=weekVal,proto3" json:"weekVal,omitempty"`
	MonVal               float32  `protobuf:"fixed32,2,opt,name=monVal,proto3" json:"monVal,omitempty"`
	YearVal              float32  `protobuf:"fixed32,3,opt,name=yearVal,proto3" json:"yearVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatisticalInfo) Reset()         { *m = StatisticalInfo{} }
func (m *StatisticalInfo) String() string { return proto.CompactTextString(m) }
func (*StatisticalInfo) ProtoMessage()    {}
func (*StatisticalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{3}
}

func (m *StatisticalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticalInfo.Unmarshal(m, b)
}
func (m *StatisticalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticalInfo.Marshal(b, m, deterministic)
}
func (m *StatisticalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticalInfo.Merge(m, src)
}
func (m *StatisticalInfo) XXX_Size() int {
	return xxx_messageInfo_StatisticalInfo.Size(m)
}
func (m *StatisticalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticalInfo proto.InternalMessageInfo

func (m *StatisticalInfo) GetWeekVal() float32 {
	if m != nil {
		return m.WeekVal
	}
	return 0
}

func (m *StatisticalInfo) GetMonVal() float32 {
	if m != nil {
		return m.MonVal
	}
	return 0
}

func (m *StatisticalInfo) GetYearVal() float32 {
	if m != nil {
		return m.YearVal
	}
	return 0
}

func init() {
	proto.RegisterEnum("Event", Event_name, Event_value)
	proto.RegisterEnum("CodeType", CodeType_name, CodeType_value)
	proto.RegisterType((*Code)(nil), "Code")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Info)(nil), "Info")
	proto.RegisterType((*StatisticalInfo)(nil), "StatisticalInfo")
}

func init() {
	proto.RegisterFile("Common/msg.proto", fileDescriptor_ea6b1f2ffa71fb5f)
}

var fileDescriptor_ea6b1f2ffa71fb5f = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0xeb, 0xb5, 0x93, 0x34, 0x03, 0x4a, 0x57, 0x03, 0x44, 0x06, 0x51, 0x29, 0xe4, 0x14,
	0xf5, 0x50, 0x24, 0x38, 0x70, 0xe1, 0x12, 0x39, 0x4b, 0xb0, 0x14, 0x9c, 0x74, 0xed, 0x44, 0xea,
	0x01, 0x59, 0xa6, 0x5e, 0x2a, 0x8b, 0xd8, 0x6b, 0xc5, 0xa6, 0x51, 0xfe, 0x23, 0x3f, 0x0a, 0xed,
	0xae, 0x2d, 0x1f, 0x08, 0xb7, 0x37, 0xdf, 0xdb, 0xf7, 0x66, 0x0f, 0x03, 0xd4, 0x93, 0x79, 0x2e,
	0x8b, 0xf7, 0x79, 0xf5, 0x78, 0x5b, 0x1e, 0x64, 0x2d, 0xa7, 0x9f, 0xc0, 0xf1, 0x64, 0x2a, 0xf0,
	0x1a, 0x9c, 0x07, 0x99, 0x0a, 0xd7, 0x9a, 0x58, 0xb3, 0xd1, 0x87, 0xe1, 0xad, 0x82, 0xd1, 0xa9,
	0x14, 0x5c, 0x63, 0xa4, 0x60, 0xe7, 0xd5, 0xa3, 0x4b, 0x26, 0xd6, 0x6c, 0xc8, 0x95, 0x9c, 0x7e,
	0x06, 0x67, 0x5b, 0x89, 0x03, 0x8e, 0x80, 0x64, 0xa9, 0x8e, 0xf5, 0x38, 0xc9, 0x52, 0x44, 0x70,
	0x8a, 0x24, 0x17, 0xcd, 0x53, 0xad, 0x55, 0xba, 0x3c, 0xa6, 0xae, 0x6d, 0xd2, 0xe5, 0x31, 0x9d,
	0xee, 0xc0, 0xf1, 0x8b, 0x9f, 0xf2, 0x5c, 0xba, 0xce, 0x9a, 0x74, 0x8f, 0x6b, 0x8d, 0x2e, 0x0c,
	0x7e, 0x57, 0xa2, 0x3e, 0x95, 0xa2, 0x69, 0x68, 0x47, 0xd5, 0xfb, 0x94, 0xec, 0x5d, 0x67, 0x62,
	0xcd, 0x08, 0x57, 0x72, 0xfa, 0x1d, 0xae, 0xc2, 0x3a, 0xa9, 0xb3, 0xaa, 0xce, 0x1e, 0x92, 0xbd,
	0x5e, 0xe1, 0xc2, 0xe0, 0x28, 0xc4, 0xaf, 0x5d, 0xb2, 0xd7, 0x7b, 0x08, 0x6f, 0x47, 0x1c, 0x43,
	0x3f, 0x97, 0x85, 0x32, 0x88, 0x36, 0x9a, 0x49, 0x25, 0x4e, 0x22, 0x39, 0x28, 0xc3, 0x36, 0x89,
	0x66, 0xbc, 0xf9, 0x43, 0xa0, 0xc7, 0x9e, 0x44, 0x51, 0x23, 0xc2, 0x88, 0xed, 0x58, 0x10, 0xc5,
	0xdf, 0xc2, 0x65, 0xec, 0x07, 0x5f, 0xd6, 0xf4, 0x02, 0xc7, 0x80, 0x86, 0x71, 0xb6, 0xf4, 0xc3,
	0x88, 0xf1, 0x98, 0xb3, 0x3b, 0x6a, 0x9d, 0xe5, 0x1b, 0x4a, 0xf0, 0x05, 0x5c, 0x19, 0xbe, 0x5a,
	0x2f, 0xfd, 0x40, 0x3f, 0xb6, 0xff, 0x85, 0x1b, 0xea, 0x74, 0x0d, 0xf3, 0xc5, 0x22, 0x5e, 0x07,
	0xcc, 0x6c, 0xec, 0xa1, 0x0b, 0x2f, 0x0d, 0xbf, 0xdb, 0x32, 0x7e, 0xaf, 0xa9, 0xae, 0xe9, 0xe3,
	0x1b, 0x18, 0xb7, 0x3b, 0xa3, 0x2d, 0x0f, 0x8c, 0xb5, 0xf2, 0xc3, 0x88, 0x0e, 0xf0, 0x35, 0xbc,
	0x32, 0x9e, 0xf7, 0x75, 0x1e, 0x2c, 0x59, 0x17, 0xbb, 0xfc, 0x9f, 0xb5, 0xa1, 0xc3, 0xee, 0x0f,
	0x0b, 0xb6, 0xea, 0x22, 0x70, 0x96, 0x6f, 0xe8, 0x33, 0x7c, 0x07, 0xd7, 0x86, 0x87, 0xd1, 0x3c,
	0xf2, 0xc3, 0x7b, 0xdf, 0x9b, 0x37, 0xbe, 0xe9, 0xa6, 0xcf, 0x6f, 0xde, 0xc2, 0x65, 0x7b, 0x67,
	0x38, 0x00, 0x9b, 0x71, 0x4e, 0x2f, 0x94, 0x08, 0xb7, 0x1e, 0xb5, 0x7e, 0xf4, 0xf5, 0x85, 0x7e,
	0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x84, 0x6a, 0xbe, 0x53, 0xb5, 0x02, 0x00, 0x00,
}
