// Code generated by protoc-gen-go. DO NOT EDIT.
// source: JiZhangBo/jiZhangBo.proto

package jiZhangBo

import (
	Common "../Common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterReq struct {
	User                 *Common.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUser() *Common.User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterRep struct {
	Code                 *Common.Code `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterRep) Reset()         { *m = RegisterRep{} }
func (m *RegisterRep) String() string { return proto.CompactTextString(m) }
func (*RegisterRep) ProtoMessage()    {}
func (*RegisterRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{1}
}

func (m *RegisterRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRep.Unmarshal(m, b)
}
func (m *RegisterRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRep.Marshal(b, m, deterministic)
}
func (m *RegisterRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRep.Merge(m, src)
}
func (m *RegisterRep) XXX_Size() int {
	return xxx_messageInfo_RegisterRep.Size(m)
}
func (m *RegisterRep) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRep.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRep proto.InternalMessageInfo

func (m *RegisterRep) GetCode() *Common.Code {
	if m != nil {
		return m.Code
	}
	return nil
}

type LoginReq struct {
	User                 *Common.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{2}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUser() *Common.User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginRep struct {
	Code                 *Common.Code            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	User                 *Common.User            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	SInfo                *Common.StatisticalInfo `protobuf:"bytes,3,opt,name=sInfo,proto3" json:"sInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LoginRep) Reset()         { *m = LoginRep{} }
func (m *LoginRep) String() string { return proto.CompactTextString(m) }
func (*LoginRep) ProtoMessage()    {}
func (*LoginRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{3}
}

func (m *LoginRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRep.Unmarshal(m, b)
}
func (m *LoginRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRep.Marshal(b, m, deterministic)
}
func (m *LoginRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRep.Merge(m, src)
}
func (m *LoginRep) XXX_Size() int {
	return xxx_messageInfo_LoginRep.Size(m)
}
func (m *LoginRep) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRep.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRep proto.InternalMessageInfo

func (m *LoginRep) GetCode() *Common.Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *LoginRep) GetUser() *Common.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginRep) GetSInfo() *Common.StatisticalInfo {
	if m != nil {
		return m.SInfo
	}
	return nil
}

type QueryInfoReq struct {
	Usetype              string   `protobuf:"bytes,1,opt,name=usetype,proto3" json:"usetype,omitempty"`
	StartTime            int32    `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int32    `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryInfoReq) Reset()         { *m = QueryInfoReq{} }
func (m *QueryInfoReq) String() string { return proto.CompactTextString(m) }
func (*QueryInfoReq) ProtoMessage()    {}
func (*QueryInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{4}
}

func (m *QueryInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryInfoReq.Unmarshal(m, b)
}
func (m *QueryInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryInfoReq.Marshal(b, m, deterministic)
}
func (m *QueryInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInfoReq.Merge(m, src)
}
func (m *QueryInfoReq) XXX_Size() int {
	return xxx_messageInfo_QueryInfoReq.Size(m)
}
func (m *QueryInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInfoReq proto.InternalMessageInfo

func (m *QueryInfoReq) GetUsetype() string {
	if m != nil {
		return m.Usetype
	}
	return ""
}

func (m *QueryInfoReq) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *QueryInfoReq) GetEndTime() int32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type AddInfoReq struct {
	Info                 *Common.Info `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddInfoReq) Reset()         { *m = AddInfoReq{} }
func (m *AddInfoReq) String() string { return proto.CompactTextString(m) }
func (*AddInfoReq) ProtoMessage()    {}
func (*AddInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{5}
}

func (m *AddInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInfoReq.Unmarshal(m, b)
}
func (m *AddInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInfoReq.Marshal(b, m, deterministic)
}
func (m *AddInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInfoReq.Merge(m, src)
}
func (m *AddInfoReq) XXX_Size() int {
	return xxx_messageInfo_AddInfoReq.Size(m)
}
func (m *AddInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddInfoReq proto.InternalMessageInfo

func (m *AddInfoReq) GetInfo() *Common.Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type DelInfoReq struct {
	Idlist               []int32  `protobuf:"varint,1,rep,packed,name=idlist,proto3" json:"idlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelInfoReq) Reset()         { *m = DelInfoReq{} }
func (m *DelInfoReq) String() string { return proto.CompactTextString(m) }
func (*DelInfoReq) ProtoMessage()    {}
func (*DelInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{6}
}

func (m *DelInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelInfoReq.Unmarshal(m, b)
}
func (m *DelInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelInfoReq.Marshal(b, m, deterministic)
}
func (m *DelInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelInfoReq.Merge(m, src)
}
func (m *DelInfoReq) XXX_Size() int {
	return xxx_messageInfo_DelInfoReq.Size(m)
}
func (m *DelInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelInfoReq proto.InternalMessageInfo

func (m *DelInfoReq) GetIdlist() []int32 {
	if m != nil {
		return m.Idlist
	}
	return nil
}

type DelInfoRep struct {
	Code                 *Common.Code `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Idlist               []int32      `protobuf:"varint,2,rep,packed,name=idlist,proto3" json:"idlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DelInfoRep) Reset()         { *m = DelInfoRep{} }
func (m *DelInfoRep) String() string { return proto.CompactTextString(m) }
func (*DelInfoRep) ProtoMessage()    {}
func (*DelInfoRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{7}
}

func (m *DelInfoRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelInfoRep.Unmarshal(m, b)
}
func (m *DelInfoRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelInfoRep.Marshal(b, m, deterministic)
}
func (m *DelInfoRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelInfoRep.Merge(m, src)
}
func (m *DelInfoRep) XXX_Size() int {
	return xxx_messageInfo_DelInfoRep.Size(m)
}
func (m *DelInfoRep) XXX_DiscardUnknown() {
	xxx_messageInfo_DelInfoRep.DiscardUnknown(m)
}

var xxx_messageInfo_DelInfoRep proto.InternalMessageInfo

func (m *DelInfoRep) GetCode() *Common.Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *DelInfoRep) GetIdlist() []int32 {
	if m != nil {
		return m.Idlist
	}
	return nil
}

type ChangeInfoReq struct {
	Infoid               int32    `protobuf:"varint,1,opt,name=infoid,proto3" json:"infoid,omitempty"`
	Changeval            float32  `protobuf:"fixed32,2,opt,name=changeval,proto3" json:"changeval,omitempty"`
	Changeusetype        string   `protobuf:"bytes,3,opt,name=changeusetype,proto3" json:"changeusetype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeInfoReq) Reset()         { *m = ChangeInfoReq{} }
func (m *ChangeInfoReq) String() string { return proto.CompactTextString(m) }
func (*ChangeInfoReq) ProtoMessage()    {}
func (*ChangeInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{8}
}

func (m *ChangeInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeInfoReq.Unmarshal(m, b)
}
func (m *ChangeInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeInfoReq.Marshal(b, m, deterministic)
}
func (m *ChangeInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeInfoReq.Merge(m, src)
}
func (m *ChangeInfoReq) XXX_Size() int {
	return xxx_messageInfo_ChangeInfoReq.Size(m)
}
func (m *ChangeInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeInfoReq proto.InternalMessageInfo

func (m *ChangeInfoReq) GetInfoid() int32 {
	if m != nil {
		return m.Infoid
	}
	return 0
}

func (m *ChangeInfoReq) GetChangeval() float32 {
	if m != nil {
		return m.Changeval
	}
	return 0
}

func (m *ChangeInfoReq) GetChangeusetype() string {
	if m != nil {
		return m.Changeusetype
	}
	return ""
}

type ChangeInfoRep struct {
	Code                 *Common.Code `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *Common.Info `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChangeInfoRep) Reset()         { *m = ChangeInfoRep{} }
func (m *ChangeInfoRep) String() string { return proto.CompactTextString(m) }
func (*ChangeInfoRep) ProtoMessage()    {}
func (*ChangeInfoRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{9}
}

func (m *ChangeInfoRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeInfoRep.Unmarshal(m, b)
}
func (m *ChangeInfoRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeInfoRep.Marshal(b, m, deterministic)
}
func (m *ChangeInfoRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeInfoRep.Merge(m, src)
}
func (m *ChangeInfoRep) XXX_Size() int {
	return xxx_messageInfo_ChangeInfoRep.Size(m)
}
func (m *ChangeInfoRep) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeInfoRep.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeInfoRep proto.InternalMessageInfo

func (m *ChangeInfoRep) GetCode() *Common.Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ChangeInfoRep) GetInfo() *Common.Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type InfoList struct {
	Infolist             []*Common.Info `protobuf:"bytes,1,rep,name=infolist,proto3" json:"infolist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InfoList) Reset()         { *m = InfoList{} }
func (m *InfoList) String() string { return proto.CompactTextString(m) }
func (*InfoList) ProtoMessage()    {}
func (*InfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{10}
}

func (m *InfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoList.Unmarshal(m, b)
}
func (m *InfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoList.Marshal(b, m, deterministic)
}
func (m *InfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoList.Merge(m, src)
}
func (m *InfoList) XXX_Size() int {
	return xxx_messageInfo_InfoList.Size(m)
}
func (m *InfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoList.DiscardUnknown(m)
}

var xxx_messageInfo_InfoList proto.InternalMessageInfo

func (m *InfoList) GetInfolist() []*Common.Info {
	if m != nil {
		return m.Infolist
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "RegisterReq")
	proto.RegisterType((*RegisterRep)(nil), "RegisterRep")
	proto.RegisterType((*LoginReq)(nil), "LoginReq")
	proto.RegisterType((*LoginRep)(nil), "LoginRep")
	proto.RegisterType((*QueryInfoReq)(nil), "QueryInfoReq")
	proto.RegisterType((*AddInfoReq)(nil), "AddInfoReq")
	proto.RegisterType((*DelInfoReq)(nil), "DelInfoReq")
	proto.RegisterType((*DelInfoRep)(nil), "DelInfoRep")
	proto.RegisterType((*ChangeInfoReq)(nil), "ChangeInfoReq")
	proto.RegisterType((*ChangeInfoRep)(nil), "ChangeInfoRep")
	proto.RegisterType((*InfoList)(nil), "InfoList")
}

func init() {
	proto.RegisterFile("JiZhangBo/jiZhangBo.proto", fileDescriptor_2451c90a91c96d3a)
}

var fileDescriptor_2451c90a91c96d3a = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x4f, 0xea, 0x40,
	0x14, 0x85, 0x43, 0x4b, 0x79, 0x70, 0x79, 0x24, 0xa4, 0x8b, 0x97, 0xf2, 0xe2, 0x02, 0x1b, 0x54,
	0x36, 0x42, 0xa2, 0x3f, 0xc0, 0x28, 0xba, 0xd0, 0xb0, 0x71, 0xd4, 0x8d, 0x2b, 0x2b, 0x73, 0x29,
	0xa3, 0x6d, 0x07, 0x3a, 0x83, 0x09, 0xff, 0xde, 0xcc, 0xad, 0x53, 0x68, 0x48, 0x70, 0xd7, 0xf3,
	0xdd, 0xd3, 0x73, 0x3b, 0x67, 0x0a, 0xbd, 0x07, 0xf1, 0xba, 0x88, 0xb2, 0xf8, 0x46, 0x8e, 0x3f,
	0xec, 0xd3, 0x68, 0x99, 0x4b, 0x2d, 0xff, 0x77, 0x27, 0x32, 0x4d, 0x65, 0x36, 0x4e, 0x55, 0x5c,
	0x90, 0x70, 0x08, 0x6d, 0x86, 0xb1, 0x50, 0x1a, 0x73, 0x86, 0x2b, 0xbf, 0x07, 0xf5, 0xb5, 0xc2,
	0x3c, 0xa8, 0xf5, 0x6b, 0xc3, 0xf6, 0x85, 0x37, 0x7a, 0x51, 0x98, 0x33, 0x42, 0x55, 0xe7, 0xd2,
	0x38, 0x67, 0x92, 0x63, 0xe9, 0x9c, 0x48, 0x8e, 0x8c, 0x50, 0x78, 0x02, 0xcd, 0xa9, 0x8c, 0x45,
	0xb6, 0x1b, 0xe8, 0xec, 0x07, 0x2e, 0x4a, 0xdb, 0xa1, 0xb4, 0x03, 0x09, 0xfe, 0x29, 0x78, 0xea,
	0x3e, 0x9b, 0xcb, 0xc0, 0xa5, 0x59, 0x77, 0xf4, 0xa4, 0x23, 0x2d, 0x94, 0x16, 0xb3, 0x28, 0x31,
	0x9c, 0x15, 0xe3, 0xf0, 0x0d, 0xfe, 0x3e, 0xae, 0x31, 0xdf, 0x10, 0xc3, 0x95, 0x1f, 0xc0, 0x9f,
	0xb5, 0x42, 0xbd, 0x59, 0x16, 0x0b, 0x5b, 0xcc, 0x4a, 0xff, 0x08, 0x5a, 0x4a, 0x47, 0xb9, 0x7e,
	0x16, 0x29, 0xd2, 0x46, 0x8f, 0x6d, 0x81, 0x79, 0x0f, 0x33, 0x4e, 0x33, 0x97, 0x66, 0x56, 0x86,
	0x67, 0x00, 0xd7, 0x9c, 0xdb, 0xfc, 0x1e, 0xd4, 0x85, 0xf9, 0x2c, 0x7b, 0x1a, 0xe2, 0x84, 0xc2,
	0x01, 0xc0, 0x2d, 0x26, 0xd6, 0xf8, 0x0f, 0x1a, 0x82, 0x27, 0x42, 0xe9, 0xa0, 0xd6, 0x77, 0x87,
	0x1e, 0xfb, 0x51, 0xe1, 0xd5, 0x8e, 0xeb, 0x60, 0x39, 0xdb, 0x00, 0xa7, 0x12, 0xf0, 0x09, 0x9d,
	0x89, 0xb9, 0x79, 0xdc, 0xdd, 0x94, 0xcd, 0xa5, 0xe0, 0x94, 0x62, 0x8c, 0xa4, 0xcc, 0x81, 0x67,
	0x64, 0xfc, 0x8a, 0x12, 0x3a, 0xb0, 0xc3, 0xb6, 0xc0, 0x1f, 0x40, 0xa7, 0x10, 0xb6, 0x2e, 0x97,
	0xea, 0xaa, 0xc2, 0xf0, 0xae, 0xba, 0xec, 0xb7, 0xdb, 0xa4, 0x6a, 0x9c, 0xfd, 0x6a, 0xce, 0xa1,
	0x69, 0xd4, 0x54, 0x28, 0xed, 0x1f, 0x43, 0xd3, 0xb0, 0xb2, 0x9a, 0xd2, 0x5a, 0xe2, 0xf7, 0x06,
	0xfd, 0xc0, 0x97, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x27, 0x6a, 0x76, 0x18, 0xef, 0x02, 0x00,
	0x00,
}
